default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password: gerard1995
  database: data_access
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
